version: "3.7"
services:
    db:
        image: postgres
        environment:
            PGPASSWORD: postgres
            PGUSER: postgres
            PGDATABASE: articles
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    web:
        image: blured75/node-web-app
        depends_on: ["db"]
        environment:
            PGPASSWORD: postgres
            PGUSER: postgres
            PGDATABASE: articles
        ports:
            - "3000:3000"
